### PR TITLE
Replace getNameTag() with getDisplayName()

### PR DESCRIPTION
**Pull request by Aericio**
image
image
If you use getNameTag(), it'll show the color codes on quit.
If you use getDisplayName(), it will just get their nickname instead. In case the nickname uses color codes, it cleans the formatting with TextFormat::clean().

Optionally, you could just use getName() if you wanted and not need to use TextFormat::clean().

### CODE REVIEW

**Comment by Aericio** [comment]
Wait, do you want PurePerms ranks to be shown?

**Comment by NiekertDev** [comment]
Actually, atm I'm having a veeery long break, but I don't think people want to show pureperms name, but can you tell me why it returns the pureperms name only when you left?

P.S. Most of the plugin needs to be rewritten so a event isn't being called when not enabled, part of the reason is that it is my first plugin ever made and I learned a lot while making it

**Review by NiekertDev — APPROVED** [review]
Can be merged into master, see above for answer

**Comment by NiekertDev** [comment]
Thank you for helping me! You partly fixed #29

**Comment by Aericio** [comment]
Most likely due to PureChat updating the tags *after* the player had joined the server. You're probably getting the nametag the moment they connect... that's my guess.

**Pull request merged**
